version: "3.8"

services:
  db:
    image: postgres
    container_name: musclemate-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./musclemate-backend
    container_name: musclemate-back
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./musclemate-backend/src/:/app/src
      - ./musclemate-backend/local_settings.docker.py:/app/local_settings.py
  frontend:
    build: ./musclemate-frontend
    container_name: musclemate-front
    ports:
      - "127.0.0.1:5173:5173"
    working_dir: /app
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./musclemate-frontend/src/:/app/src
      - ./musclemate-frontend/.env.docker:/app/.env

volumes:
  postgres_data:
